export const PACEAPP_BASEURL =
  "https://lime-clever-peacock.cyclic.app/api/v1/creators";
export const PACEAPP_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ZDcyNGNiZjU4NzcxZTczMWNmNzY0MCIsImVtYWlsIjoiZGV4bmlzMzBAbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJJc2FhYyIsInJvbGUiOiJjcmVhdG9yIn0sImlhdCI6MTY5MjU1NDE5OCwiZXhwIjoxNjkyNTk3Mzk4fQ.IyBi2-UNJzW0_mMW8dSCq5VNfCdoL1CUy-cEpqb7KQk";
